Adding Xaenalt as maintainer for model serving
opendatahub-io/org-management pull request #144
Opened 2023-09-19 17:44 UTC by Xaenalt

## Description
Need the power to fork repos to ODH, notably OVMS as we bring it up to date and in line with our build processes

2023-09-20 02:14 UTC, anishasthana commented
@Xaenalt This won't give you the ability to fork repos to the ODH org as I understand it. That's reserved solely for ODH admins -- https://github.com/opendatahub-io/org-management/blob/main/config/opendatahub-io/org.yaml#L3-L13

2023-09-25 19:59 UTC, Xaenalt commented
Ok, updated with even more superpowers xD

2023-09-25 20:01 UTC, accorvin requested changes

2023-09-25 20:01 UTC, accorvin commented on config/opendatahub-io/org.yaml
> +    - Xaenalt
We keep the list of org admins quite small. I think you don't need this.

2023-09-25 20:01 UTC, accorvin commented on config/opendatahub-io/org.yaml
>          repos:
I think you'll need to add the new repo to this list.

2023-09-25 20:07 UTC, Xaenalt commented
Ok, how's this look?

2023-09-25 20:07 UTC, accorvin approved these changes

2023-09-25 20:11 UTC, heyselbi approved these changes

2023-09-25 20:11 UTC, heyselbi commented
/lgtm

2023-09-25 20:11 UTC, heyselbi commented
/approve

2023-09-25 20:12 UTC, merged